In [11]:
# from string import ascii_uppercase  as alphabets
# import json
# import regex as re
# from tqdm.notebook import tqdm
# from itertools import permutations, product, combinations_with_replacement, combinations
import numpy as np
# import tensorflow as tf

In [7]:
if not len(np.array([])):
    print("ok")

ok


In [17]:
if [2, 2, 2, 2, 2] == [2] * 5:
    print("ok")

ok


In [27]:
l = [2, 2, 2, 2, 0]
l

[2, 2, 2, 2, 0]

In [28]:
len([i for i in l if i == 2])

4

In [21]:
p = np.ones(10)
p

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
l = np.array([1, 2, 3])
p[l] = 0
p

array([1., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

In [15]:
s = "[A-Z][A][A-Z]"

s.replace("A-Z", "BCD")

'[BCD][A][BCD]'

In [12]:
p = np.array([1., 2., 3.])
p

array([1., 2., 3.])

In [13]:
1 in p

True

In [5]:
len(np.array([]))

0

In [2]:
# position_dict = {"": 0}

# i = 1
# for letter in alphabets:
#     for flag in range(3):
#         position_dict[f"{letter}|{flag}"] = i
#         i += 1

# with open("state_dict_0.json", "w") as f:
#     json.dump(position_dict, f, indent=4)

In [3]:
# letter_dict = {}
# for letter in alphabets:
#     for position in range(5):
#         for flag in range(3):
#             letter_dict[f"{letter}|{position}|{flag}"] = len(letter_dict)

# with open("state_dict_1.json", "w") as f:
#     json.dump(letter_dict, f, indent=4)

In [4]:
# from src.wordle_agent.dqn_agent_0 import WordleAgent, DataConfig

In [5]:
from src.wordle_gym.env_0 import Wordle

/usr/local/lib/python3.8/dist-packages/scipy/fft/__init__.py:97: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/usr/local/lib/python3.8/dist-packages/scipy/sparse/sputils.py:17: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
/usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/local/lib/python3.8/dist-packages/fsspec/spec.py:91: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if pa_version and LooseVersion(pa_version) < LooseVersion("2.0"):
/usr/local/lib/python3.8/dist-packages/keras_preprocessing/image/utils.py:23: DeprecationWarning: NEAREST is deprecated and will be remov

In [6]:
Wordle(mode='easy').test()

Board:  [ 1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.
  1.  1.  0.  0.  0.  0.  0.  0. 42. 14.  2. 58. 55.  1.]
Mask: 5370.0
Board:  [ 1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  1.
  1.  1.  0.  1.  0.  0.  0.  0. 65. 43. 37. 14. 52.  2.]
Mask: 562.0
Board:  [ 1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  1.
  1.  1.  0.  1.  0.  0.  0.  0.  2. 52.  2. 37. 15.  3.]
Mask: 505.0
Board:  [ 1.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.  1.
  1.  1.  0.  1.  0.  0.  0.  0. 19. 43. 43. 46. 55.  4.]
Mask: 505.0
Board:  [ 1.  0.  0.  0.  1.  0.  1.  0.  0.  1.  0.  0.  1.  1.  1.  1.  0.  1.
  1.  1.  0.  1.  0.  0.  0.  0. 28.  3. 41. 14. 55.  5.]
Mask: 297.0
Board:  [ 1.  0.  0.  0.  1.  0.  1.  0.  0.  1.  0.  1.  1.  1.  1.  1.  0.  1.
  1.  1.  0.  1.  0.  0.  0.  0. 58. 14. 34.  2. 15.  6.]
Mask: 152.0
Board:  [ 1.  0.  0.  1.  1.  0.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  0.  1.
  1.  1.  0.